import com.google.gson.JsonObject;
import com.theja.jsonsearch.utils.JsonUtils;
import com.theja.jsonsearch.controller.Search;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.util.Set;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class SearchMain {
    private static final String USERS = "users";
    private static final String TICKETS = "tickets";
    private static final String ORGS = "organizations";
    private static final String QUIT = "quit";
    private static final List<String> WELCOME_MENU;
    static {
        WELCOME_MENU = new ArrayList<>();
        WELCOME_MENU.add(USERS);
        WELCOME_MENU.add(TICKETS);
        WELCOME_MENU.add(ORGS);
        WELCOME_MENU.add(QUIT);
    }

    public static void main(String[] args) {
        System.out.println("Welcome to Search");
        System.out.println("Type 'quit' to exit anytime, press Enter to continue" );
        while (true) {
            printWelcomeText();
            Scanner scanner = new Scanner(System.in);
            String optedCategory = scanner.nextLine().trim();
            // TODO: add condition checks on selected category
            if (QUIT.equalsIgnoreCase(optedCategory)) {
                System.exit(1);
            }
            // based on selected search category, show searchable fields
            System.out.println(
                    String.format("Below are the searchable fields for category %s, select your search term",
                            optedCategory));
            Set<String> availableFields = Search.getAvailableSearchableFieldsOnCategory(optedCategory);
            availableFields.forEach(System.out::println);
            String optedSearchTerm = scanner.nextLine().trim();
            System.out.println("Enter the search value");
            String optedSearchValue = scanner.nextLine().trim();
            try{
                List<JsonObject> searchResult =
                        Search.performSearchOperation(optedCategory, optedSearchTerm, optedSearchValue);
                JsonUtils.printResults(optedCategory, searchResult);
            }
            catch (IOException ex) {
                System.out.println("Unable to perform search currently");
            }
        }
    }


    private static void printWelcomeText() {
        System.out.println("Below are the list of categories to search for");
        WELCOME_MENU.forEach(System.out::println);
    }
}
