/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class SearchMainTest {
    @Test public void testSomeLibraryMethod() {
        SearchMain classUnderTest = new SearchMain();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
